name: release

on:
  push:
    tags:
      - main

jobs:
  build:
    runs-on: windows-2019
    permissions:
      contents: read
      steps:
        - uses: actions/checkout@v2

        - name: Setup MSBuild
          uses: microsoft/setup-msbuild@v1

        - name: Setup NuGet
          uses: NuGet/setup-nuget@v1.0.5
          
        - name: setup-msbuild
          uses: microsoft/setup-msbuild@v1.1

        - name: Restore Packages
          run: nuget restore Source\RW-MassAffect.sln

        - name: Build solution
          run: msbuild Source\RW-MassAffect.sln -t:rebuild -property:Configuration=Debug