name: release

on:
  push:
    tags:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      -name: Create Release Zip
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: Zip
          directory: './'
          filename: MassAffect-Release.zip
          exclusions: '/.git/*, /.gitea/*, /.vscode/*, /.vs/*, /source/*'
